name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Install node modules
        run: |
          npm install
      - name: Run CI with Lefthook
        run: |
          npm lefthook run ci-hook
      - name: Run test
        run: |
          npm test-ci
