name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node modules
        run: |
          npm install

  # Second Job
  build-android:
    needs: install-and-test
    uses: ./.github/workflows/build_android.yml
    with:
      environment: Debug
    secrets: inherit
